### ISSUE TITLE
Upload latest fixes to pip ? 

### ISSUE THREAD

**Issue by ahakanbaba** [sphinx-contrib/restbuilder#2]
Hi,  
I just realized that the newest fixes are not available to the installation via pip. 
For example this https://github.com/sphinx-contrib/restbuilder/commit/deec25c0b65f4497f5960cc84fafc970455e2d33

Could we upload the latest version of this to pip ? 
Thanks

**Comment by ahakanbaba** [comment]
I see there are bugs in the visit_reference implementation that handles links correctly 

A text like 

     `Wavefront_ <https://www.wavefront.com>`_

Results in this error 

```
# Sphinx version: 1.7.4
# Python version: 2.7.14 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.9.6
# Last messages:
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [ 33%] README
# Loaded extensions:
#   sphinxcontrib.restbuilder (unknown version) from /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/restbuilder.pyc
#   alabaster (0.7.10) from /usr/local/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinxcontrib.programoutput (unknown version) from /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/programoutput/__init__.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 338, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 399, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 436, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 445, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/builders/rst.py", line 130, in write_doc
    self.writer.write(doctree, destination)
  File "/usr/local/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/writers/rst.py", line 40, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/writers/rst.py", line 712, in visit_reference
    self.add_text('`%s <%s>`_' % (node['name'], node['refuri']))
  File "/usr/local/lib/python2.7/site-packages/docutils/nodes.py", line 567, in __getitem__
    return self.attributes[key]
KeyError: u'name'
```

It probably requires some work before being uploaded to pip.

**Comment by chrisjbremner** [comment]
@macfreek, do you think you could bump the version on PyPi so that Python3 users can use this package?
